

module Formula.Abs where

-- Haskell module generated by the BNF converter




newtype PIdent = PIdent ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
data Formula
    = Implies Formula Formula
    | Implied Formula Formula
    | Iff Formula Formula
    | Until Formula Formula
    | Release Formula Formula
    | Since Formula Formula
    | Triggered Formula Formula
    | And Formula Formula
    | Or Formula Formula
    | Next Formula
    | Eventually Formula
    | Always Formula
    | Yesterday Formula
    | Wyesterday Formula
    | Once Formula
    | Historically Formula
    | Not Formula
    | Atom PIdent
    | Bool Boolean
  deriving (Eq, Ord, Show, Read)

data Boolean = Boolean_True | Boolean_False
  deriving (Eq, Ord, Show, Read)

